# Generated by Django 6.0.4 on 2026-04-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0004_deployment_container_port_project_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("local_path", models.CharField(max_length=1024)),
                ("current_branch", models.CharField(default="main", max_length=255)),
                ("last_pull_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repository",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
            },
        ),
    ]
