# Generated by Django 6.0.4 on 2026-04-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_deployment_hot_reload"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host_path",
                    models.CharField(
                        help_text="Absolute path on the host machine.", max_length=1024
                    ),
                ),
                (
                    "container_path",
                    models.CharField(
                        default="/app",
                        help_text="Path inside the container where the host_path will be mounted.",
                        max_length=1024,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_source",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
