# Generated by Django 6.0.4 on 2026-04-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hostname_or_ip", models.CharField(max_length=255, unique=True)),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Maintenance"),
                            ("ERROR", "Error"),
                        ],
                        default="OFFLINE",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("os_info", models.CharField(blank=True, max_length=255, null=True)),
                ("cpu_cores", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "memory_total",
                    models.BigIntegerField(
                        blank=True, help_text="Total memory in bytes", null=True
                    ),
                ),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Server",
                "verbose_name_plural": "Servers",
                "ordering": ["-created_at"],
            },
        ),
    ]
