# Generated by Django 6.0.4 on 2026-04-22 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="cpu_cores",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="last_heartbeat",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="memory_total",
            field=models.BigIntegerField(
                blank=True,
                help_text="Total memory in bytes",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("MAINTENANCE", "Maintenance"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OFFLINE",
                max_length=20,
            ),
        ),
    ]
