# Generated by Django 6.0.6 on 2026-06-12 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_server_cpu_cores_alter_server_last_heartbeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
    ]
