# Generated by Django 6.0.5 on 2026-05-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_server_cpu_cores_alter_server_last_heartbeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OFFLINE",
                max_length=20,
            ),
        ),
    ]
