# Generated by Django 6.0.5 on 2026-06-03 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servers", "0002_alter_server_cpu_cores_alter_server_last_heartbeat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="status",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Online"),
                    ("OFFLINE", "Offline"),
                    ("ERROR", "Error"),
                ],
                db_index=True,
                default="OFFLINE",
                max_length=20,
            ),
        ),
    ]
