# Generated by Django 6.0.4 on 2026-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="network_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
