# Generated by Django 6.0.4 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_network_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="container_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTING", "Starting"),
                    ("RUNNING", "Running"),
                    ("STOPPING", "Stopping"),
                    ("STOPPED", "Stopped"),
                    ("RESTARTING", "Restarting"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
