# Generated by Django 6.0.4 on 2026-04-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_deployment_container_id_alter_deployment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="container_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="project",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
