# Generated by Django 6.0.4 on 2026-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_deployment_container_port_project_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="hot_reload",
            field=models.BooleanField(default=False),
        ),
    ]
