# Generated by Django 6.0.5 on 2026-05-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_deployment_hot_reload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("redis", "Redis")],
                        max_length=20,
                    ),
                ),
                ("db_name", models.CharField(max_length=255)),
                ("db_user", models.CharField(max_length=255)),
                ("db_password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="databases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "engine")},
            },
        ),
    ]
