# Generated by Django 6.0.6 on 2026-06-07 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_deployment_hot_reload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("redis", "Redis")],
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("redis", "Redis")],
                        max_length=20,
                    ),
                ),
                ("db_name", models.CharField(default="khamal", max_length=255)),
                ("db_user", models.CharField(default="khamal", max_length=255)),
                ("db_password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="databases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "engine")},
            },
        ),
    ]
