# Generated by Django 6.0.5 on 2026-05-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_deployment_hot_reload"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="db_postgres_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="db_redis_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
