[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cacheDirectories = [
  "node_modules",
  "/root/.cache/pip",
  "/root/.cache/npm",
  "/root/.cache/pnpm",
  "/root/.cache/yarn"
]

[phases.build]
cacheDirectories = [
  "node_modules",
  ".next/cache",
  "/root/.cache/pip",
  "/root/.cache/npm",
  "/root/.cache/pnpm",
  "/root/.cache/yarn"
]
