[phases.setup]
nixPkgs = ["python3", "nodejs"]

[phases.install]
cacheDirectories = [
  "node_modules",
  "/root/.cache/pip",
  "/root/.cache/npm",
  "/root/.cache/yarn",
  "/root/.cache/pnpm",
  "/root/.bun/install/cache",
  "/root/.cache/deno"
]

[phases.build]
cacheDirectories = [
  "node_modules",
  ".next/cache",
  "/root/.cache/pip",
  "/root/.cache/npm",
  "/root/.cache/yarn",
  "/root/.cache/pnpm",
  "/root/.bun/install/cache",
  "/root/.cache/deno"
]
