# Generated by Django 6.0.4 on 2026-04-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_support", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosticrequest",
            name="is_successful",
        ),
    ]
