# Generated by Django 6.0.4 on 2026-04-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhiteLabelConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default Configuration", max_length=255),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="white_label/logos/"
                    ),
                ),
                (
                    "custom_css",
                    models.TextField(
                        blank=True,
                        help_text="Custom CSS to be injected into templates.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one configuration can be active at a time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "White Label Configuration",
                "verbose_name_plural": "White Label Configurations",
            },
        ),
    ]
